### ISSUE TITLE
Improvement: Avoid repetition of references in the bibliography

### ISSUE THREAD

**Issue by bcdavasconcelos** [pandoc-ext/multibib#2]
In some cases, a reference may be present in more than one bibliography file. Would it be possible to avoid this repetition? That is, if a reference has already appeared in a previous bibliography section/file, to avoid displaying it again.

```
## Bib 1

::: {#refs-some-references}                       <!-- if it appears here -->
:::

## Bib 2

::: {#refs-other-references}                       <!-- avoid displaying it again here -->
:::
```

I have no idea if this is feasible, to be honest.

**Comment by tarleb** [comment]
It would be doable, but I'm not sure if it should be part of this filter, as the duplicate might be intentional.
It would probably be best to produce a separate file that does not contain those duplicates.

**Comment by bcdavasconcelos** [comment]
Fair enough 🙂 By the way, sorry I could not find a way to tag this as a suggestion rather than an issue.

**Comment by tarleb** [comment]
That's on me, I haven't taken the time yet to define some reasonable templates for issues and feature requests.
