### ISSUE TITLE
failure to compile pdf

### ISSUE THREAD

**Issue by hollzzar** [pandoc-ext/multibib#7]
I am using R version 4.2.2 and pandoc version 3.1.1 on MacOS Big Sur 11.6. 

I am trying to use this filter to add multiple bibliographies to my academic CV with the `vitae` package. I link to a reproducible example of my issue below.

When I try to compile the document, I get the following output:

[WARNING] Citeproc: Citation with no printed form: 
[WARNING] Citeproc: Citation with no printed form: 
! You can't use `\vadjust' in vertical mode.
l.130 \leavevmode\vadjust
                          pre{\hypertarget{ref-4}{}}% 

Error: LaTeX failed to compile cv_temp_test.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See cv_temp_test.log for more info.
Execution halted

I have successfully used this lua filter to knit a Word Document with Bookdown, so this appears to be an issue with knitting to a PDF specifically.

[cv.zip](https://github.com/pandoc-ext/multibib/files/12373210/cv.zip)

**Comment by tarleb** [comment]
Apologies for the late reply.

The filter has no special handling for LaTeX, so the problem is most likely not related to the processing here.

Please reopen if you think that there really is a bug to be fixed here, and not in the other components of your setup.
