### ISSUE TITLE
quarto complaining that bibliography field should be a string

### ISSUE THREAD

**Issue by bbolker** [pandoc-ext/multibib#9]
I'm sure I'm doing something silly here, but with Quarto 1.3.450, pandoc 3.1.8, `quarto render books.qmd --to markdown` gives:

```
ERROR: Validation of YAML front matter failed.
ERROR: In file books.qmd
(line 7, columns 4--24) Field "bibliography" has value main: main_books.bib, which must instead be a string
6: bibliography:
7:    main: main_books.bib
     ~~~~~~~~~~~~~~~~~~~~~
8: filters:
✖ The value main: main_books.bib is of type object.
ℹ The error happened in location bibliography.

ERROR: Render failed due to invalid YAML.
```

Should I be asking for help here or on Quarto forums?

Test file (I don't think you need the bib file to diagnose this ...?)

```
---
title: "Annotated bibliography"
bibliography:
   main: main_books.bib
filters:
   - multibib
---

## Primary references

::: {#refs-main}
:::
```

**Comment by Pakillo** [comment]
I think this is the same issue: https://github.com/pandoc-ext/multibib/issues/1

A quick fix is to add `validate-yaml: false` to the document YAML. See brief discussion [here](https://github.com/quarto-dev/quarto-cli/issues/4139)

HTH

**Comment by bbolker** [comment]
Thanks! Should have looked in closed as well as open issues. If I get to it maybe I'll submit a pull request to add this information to the README (as it seems it will trip up any Quarto users ... ??)

**Comment by Pakillo** [comment]
Yes, probably a good idea (I hit the same wall a few months ago :)

**Comment by bbolker** [comment]
[opened a pull request](https://github.com/pandoc-ext/multibib/pull/10)
